### PR TITLE
TEST: testing branch permissions

### PR DESCRIPTION
**Pull request by alesparza**
do not merge

### CODE REVIEW

**Comment by alesparza** [comment]
Write access allows pushing new branches directly to github.  Put there doesn't seem to be a merge lock-out if the review hasn't been complete.  Should be an option in the Branch setting page.

image.

This is what it looks like when setup correctly.

image

**Comment by alesparza** [comment]
Okay, looks good now

**Review by kuang-da — COMMENTED** [review]
Now the branch protection seems working. Thank you, Antonio.

**Comment by kuang-da** [comment]
Close this testing PR since it works as expected now.

**Pull request closed without merging**
