### PR TITLE
fix: #2 use clang-10

### PR DESCRIPTION
**Pull request by alesparza**
using Derek's recommended changes to update the VM to use clang-10 to match the autograder builds

### CODE REVIEW

**Comment by alesparza** [comment]
Confirmed that this vagrant file loads clang-10

image

**Comment by alesparza** [comment]
100% for project1a

**Comment by alesparza** [comment]
100% for project1b

**Comment by alesparza** [comment]
project1c does not have an autograder loaded in gradescope

**Comment by alesparza** [comment]
100% for project3a

**Comment by alesparza** [comment]
100% for project2a and project2b

**Comment by alesparza** [comment]
project3b and project3c failed (good thing I already passed the class)
proxy and static tests did pass, seems like the concurrency isn't up to par.  locally I'm getting a couple dozen connections before it crashes

**Comment by alesparza** [comment]
Looks like there were no issues compiling, but my concurrency code isn't up to snuff.  They do pass the static and proxy tests though, so I think the autograder and clang are okay, so the new vagrantfile is ready for review (I don't have write access to make the edits myself)

**Comment by kuang-da** [comment]
Great work with detailed testing.

LGTM!

**Pull request merged**
